# Generated by Django 3.0.3 on 2020-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_account', models.CharField(max_length=20)),
                ('to_account', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
