# Generated by Django 3.0.3 on 2020-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='check_me_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
