# Generated by Django 3.0.3 on 2020-03-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200324_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='check_me_out',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
    ]
